Refactor org.instaslice string using the constant
openshift/instaslice-operator pull request #128
Opened 2024-09-26 12:40 UTC by hasanawad94

This pr refactors the use cases for "org.instaslice" in code to use the defined constant
#21

2024-09-26 13:21 UTC, harche commented
@hasanawad94 thanks for the PR. 

/ok-to-test

/assign @sairameshv

2024-09-26 13:43 UTC, hasanawad94 commented
Will see about the tests

2024-09-26 13:45 UTC, sairameshv requested changes

2024-09-26 13:45 UTC, sairameshv commented on internal/controller/instaslice_daemonset_test.go
> +	assert.False(t, exists, "resource '%suid-1' should be deleted from the node's capacity", , orgInstaslicePrefix)
```suggestion
	assert.False(t, exists, fmt.Sprintf("resource '%suid-1' should be deleted from the node's capacity", orgInstaslicePrefix))
```

2024-09-26 13:45 UTC, sairameshv commented on test/e2e/e2e_test.go
> -			Expect(found).To(BeTrue(), "Pod does not have finalizers")
I think this line has been missed

2024-09-26 13:45 UTC, sairameshv commented on test/e2e/e2e_test.go
> +            Expect(finalizers).To(ContainElement(finalizer), "Finalizer '%s' not found on pod", finalizer)
Please check the indentation here

2024-09-26 13:45 UTC, sairameshv commented on test/e2e/e2e_test.go
> +			finalizer := orgInstaslicePrefix + "accelerator"
This constant `orgInstaslicePrefix` has to be defined inside this `test/e2e` package

2024-09-26 13:45 UTC, sairameshv commented on test/e2e/e2e_test.go
> +					if strings.HasPrefix(resource, orgInstaslicePrefix) {
The constant `orgInstaslicePrefix` has to be defined in this package as a constant.

2024-09-26 13:45 UTC, sairameshv commented on test/e2e/e2e_test.go
> +			Expect(err).NotTo(HaveOccurred(), "Failed to delete %s* resources", orgInstaslicePrefix)
Once the constant `orgInstaslicePrefix` is defined,
```suggestion
			Expect(err).NotTo(HaveOccurred(), fmt.Sprintf("Failed to delete %s* resources", orgInstaslicePrefix))
```

2024-09-26 18:18 UTC, rphillips commented
Adding an internal/utils module with a GenerateInstasliceResourceName(name string) is probably worth it.

2024-09-30 15:40 UTC, mamy-CS approved these changes
/lgtm

2024-09-30 16:03 UTC, merged